#!/bin/bash

# Streamlit Cloud Deployment Guide
# This script outlines the steps to deploy on Streamlit Cloud

echo "🚀 Streamlit Cloud Deployment Steps"
echo "===================================="
echo ""
echo "STEP 1: GitHub Setup"
echo "  1. Push your repository to GitHub (https://github.com)"
echo "  2. Ensure all model files (*.pth) are in .gitignore (✅ Already done)"
echo "  3. The following files are ready:"
echo "     - streamlit_app.py (entry point)"
echo "     - packages.txt (system dependencies)"
echo "     - .streamlit/config.toml (Streamlit configuration)"
echo "     - .streamlit/secrets.toml (local development only)"
echo ""
echo "STEP 2: Prepare Models"
echo "  1. You'll need to handle models separately since they're too large for GitHub:"
echo ""
echo "  Option A: Deploy with Pre-downloaded Models (Recommended)"
echo "    - Create a 'model_cache' or use cloud storage (AWS S3, GCS, etc.)"
echo "    - Update apps/patient_chat_app.py to download models on startup"
echo ""
echo "  Option B: Use Remote Model Storage"
echo "    - Upload models to AWS S3, Google Cloud Storage, or similar"
echo "    - Add download logic to the app initialization"
echo ""
echo "STEP 3: Streamlit Cloud Setup"
echo "  1. Go to https://share.streamlit.io"
echo "  2. Sign in with your GitHub account"
echo "  3. Click 'New app'"
echo "  4. Select:"
echo "     - Repository: your-username/MedAI-ExplainableFractureDetection"
echo "     - Branch: main"
echo "     - Main file path: streamlit_app.py"
echo "  5. Click 'Deploy!'"
echo ""
echo "STEP 4: Configure Secrets in Streamlit Cloud"
echo "  1. In your deployed app, go to Settings (gear icon) > Secrets"
echo "  2. Add the following:"
echo ""
echo "     # Ollama Configuration (optional - for chat feature)"
echo "     ollama_host = \"http://your-ollama-server:11434\""
echo "     ollama_model = \"llama3\""
echo ""
echo "     # Deployment Mode"
echo "     deployment_mode = \"streamlit_cloud\""
echo ""
echo "STEP 5: Handle Model Loading"
echo "  The app currently expects models in ./outputs/"
echo ""
echo "  To deploy successfully, you need to EITHER:"
echo ""
echo "  A) Modify app to download models on startup from cloud storage:"
echo "     - Add model caching logic"
echo "     - Download from AWS S3 or similar"
echo "     - This adds ~10-20s to first load"
echo ""
echo "  B) Use a smaller model or quantized version:"
echo "     - Use model compression (ONNX, TensorRT)"
echo "     - Deploy with smaller models only"
echo ""
echo "STEP 6: Important Limitations on Streamlit Cloud"
echo "  ⚠️ Maximum disk storage: ~1 GB"
echo "  ⚠️ Model files (~1GB) cannot be included in GitHub"
echo "  ⚠️ Ollama (local LLM) won't work unless you have external Ollama server"
echo ""
echo "STEP 7: Recommended Architecture for Cloud"
echo "  1. Keep only the Streamlit frontend (~100MB with code)"
echo "  2. Store models in AWS S3 with pre-signed URLs"
echo "  3. Run Ollama on a separate VM or use cloud API (OpenAI, Anthropic)"
echo "  4. Update code to fetch models from cloud on startup (cached locally)"
echo ""
echo "✅ Quick Start for Streamlit Cloud:"
echo "  1. Modify apps/patient_chat_app.py to handle missing models gracefully"
echo "  2. Add model download/caching logic"
echo "  3. Push to GitHub"
echo "  4. Deploy on Streamlit Cloud"
echo "  5. Configure Secrets for Ollama endpoint"
echo ""
